import requests
import json


with open('/pfs/getGRAYP_2013/commit_id.txt', 'r') as file:
    pach_commit = file.read().replace('\n', '')
    
with open('/pfs/getGRAYP_2013/orcestra_id.txt', 'r') as file:
    orcestra_commit_id = file.read().replace('\n', '')
    
with open('/pfs/getGRAYP_2013/dataset.txt', 'r') as file:
    ds = file.read().replace('\n', '')
    
    
print(pach_commit)
ACCESS_TOKEN = "mjHPEyfPjYliofNuOpbeZYjCJLeIFEiKMgEFVj2i9R9SxxKdUGL3KJhJc3Sw"
r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions',
                        params={'access_token': ACCESS_TOKEN}, json={},
                        headers={"Content-Type": "application/json"})

r.status_code
r.json()
doi = r.json()['metadata']['prereserve_doi']['doi']
doi_url = r.json()['links']['bucket'] + "/" + ds + ".rds"

bucket_url = r.json()['links']['bucket']

##UPLOAD PSET

with open('/pfs/getGRAYP_2013/'+ ds + '.rds', 'rb') as fp:
    res = requests.put(
        bucket_url + '/'+ ds + '.rds',
        data=fp,
        # No headers included in the request, since it's a raw byte request
        params={'access_token': ACCESS_TOKEN},
    )
print(res.json())

##ADD METADATA

data = {
     'metadata': {
        'title': ds,
        'upload_type': 'dataset',
        'description': ds + ' PharmacoSet (PSet) generated by ORCESTRA',
        'creators': [{'name': 'Haibe-Kains, Benjamin',
                      'affiliation': 'Zenodo'}]
        }
     }
deposition_id = r.json()['id']
r = requests.put('https://sandbox.zenodo.org/api/deposit/depositions/%s' % deposition_id, params={'access_token': ACCESS_TOKEN}, data=json.dumps(data),headers={"Content-Type": "application/json"})

r.status_code

##PUBLISH TO ZENODO
r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions/%s/actions/publish' % deposition_id,
                      params={'access_token': ACCESS_TOKEN} )

##POST Request

url = 'http://www.orcestra.ca/pset/complete'
myobj = {'COMMIT': pach_commit, "ZENODO_DOI": doi, 'ORCESTRA_ID': orcestra_commit_id, 'download_link': doi_url}

x = requests.post(url, data = myobj)

print(x.text)
